// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzlMxYzTXPlzsn8ADB3DolJLfjOUQFfK8',
    appId: '1:424700093925:web:d103bd70b97e860d4ebb0c',
    messagingSenderId: '424700093925',
    projectId: 'chat-de-flutter',
    authDomain: 'chat-de-flutter.firebaseapp.com',
    storageBucket: 'chat-de-flutter.appspot.com',
    measurementId: 'G-ZXJZ7EXKTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIf-0ybpTmS7yWQ-gMMowUIk-bUQPUGK4',
    appId: '1:424700093925:android:ae59f89e12c7ab8b4ebb0c',
    messagingSenderId: '424700093925',
    projectId: 'chat-de-flutter',
    storageBucket: 'chat-de-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSoG8J5BOzWy88mQrfet4Hul7abXMi4n8',
    appId: '1:424700093925:ios:d10c1e4038cbffc84ebb0c',
    messagingSenderId: '424700093925',
    projectId: 'chat-de-flutter',
    storageBucket: 'chat-de-flutter.appspot.com',
    iosBundleId: 'belinchon.sergio.chatDeFlutter',
  );
}
